(()=>{'use strict';
const $=s=>document.querySelector(s), escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cfg=window.ENLA_CONFIG||{};const sb=window.supabase?.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
const state={tab:'overview',businessSearch:'',programSearch:'',bo:0,po:0,businesses:[],programs:[],businessTotal:0,programTotal:0,modalBusiness:null,transferProgram:null};
const fmt=n=>Number(n||0).toLocaleString('es-MX'),date=d=>d?new Date(d).toLocaleDateString('es-MX'):'—',plans={trial:'Sin plan',basic:'Básico',pro:'Pro',business:'Negocio'};
function notice(message,ok=false){const el=$('#notice');el.textContent=message;el.className='notice'+(ok?' ok':'');el.scrollIntoView({block:'nearest',behavior:'smooth'})}
async function rpc(name,args){const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message);return data}
function tab(name){state.tab=name;document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('hidden',t.id!=='tab-'+name));document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('selected',t.dataset.tab===name));const titles={overview:['Resumen general','Tu plataforma, en un solo lugar.'],businesses:['Negocios y planes','Cuentas registradas y planes de cortesía.'],programs:['Todas las tarjetas','Publicadas, borradores y clientes.'],transfer:['Transferir tarjetas','Cambia el negocio propietario y conserva los datos.']};$('#pageTitle').textContent=titles[name][0];$('#pageDesc').textContent=titles[name][1]}
function showStats(m){const items=[['Negocios registrados',m.businesses,'Cuentas'],['Tarjetas creadas',m.programs,'Total'],['Tarjetas publicadas',m.published,'Operando'],['Borradores',m.drafts,'En preparación'],['Clientes registrados',m.customers,'En toda la plataforma'],['Planes activos',m.paid,'Pagados o de cortesía']];$('#stats').innerHTML=items.map(x=>`<article class="metric"><span class="label">${x[0]}</span><strong>${fmt(x[1])}</strong><span class="pill">${x[2]}</span></article>`).join('')}
function renderBusiness(){const rows=state.businesses;$('#businessCount').textContent=fmt(state.businessTotal)+' negocios';$('#businessRows').innerHTML=rows.length?rows.map(b=>`<tr><td><strong>${escape(b.business_name)}</strong><small>${escape(b.email)}</small></td><td><span class="tag ${b.rewards_plan==='trial'?'trial':''}">${escape(plans[b.rewards_plan]||b.rewards_plan)}</span>${b.manual_plan?'<small>Plan de cortesía</small>':b.stripe_subscription_id?'<small>Stripe vinculado</small>':''}</td><td>${fmt(b.cards)} <small>${fmt(b.published)} publicadas</small></td><td>${fmt(b.customers)}</td><td>${date(b.created_at)}</td><td><button class="secondary" data-plan-id="${escape(b.id)}">Asignar plan</button></td></tr>`).join(''):'<tr><td colspan="6">No se encontraron cuentas.</td></tr>';$('#businessPage').textContent=`${state.bo+1}–${Math.min(state.bo+50,state.businessTotal)} de ${state.businessTotal}`;$('#businessPrev').disabled=state.bo===0;$('#businessNext').disabled=state.bo+50>=state.businessTotal;document.querySelectorAll('[data-plan-id]').forEach(el=>el.onclick=()=>openPlan(rows.find(b=>b.id===el.dataset.planId)))}
function renderPrograms(){const rows=state.programs;$('#programCount').textContent=fmt(state.programTotal)+' tarjetas';$('#programRows').innerHTML=rows.length?rows.map(p=>`<tr><td><strong>${escape(p.program_name)}</strong><small>${escape(p.program_type)} · ${escape(p.id)}</small></td><td><strong>${escape(p.business_name)}</strong><small>${escape(p.email)}</small></td><td><span class="tag ${p.publication_status==='published'?'':'draft'}">${p.publication_status==='published'?'Publicada':'Borrador'}</span><small>${p.status==='active'?'Activa':escape(p.status)}</small></td><td>${fmt(p.customers)}</td><td>${date(p.created_at)}</td><td><div class="card-row-actions"><a class="secondary registration-link" href="/join.html?p=${encodeURIComponent(p.id)}" target="_blank" rel="noopener noreferrer" aria-label="Abrir registro como cliente para ${escape(p.program_name)}">Probar como cliente ↗</a><button class="secondary" data-transfer-id="${escape(p.id)}">Transferir →</button></div></td></tr>`).join(''):'<tr><td colspan="6">No se encontraron tarjetas.</td></tr>';$('#programPage').textContent=`${state.po+1}–${Math.min(state.po+50,state.programTotal)} de ${state.programTotal}`;$('#programPrev').disabled=state.po===0;$('#programNext').disabled=state.po+50>=state.programTotal;$('#transferCard').innerHTML='<option value="">Selecciona una tarjeta</option>'+rows.map(p=>`<option value="${escape(p.id)}">${escape(p.program_name)} — ${escape(p.business_name)}</option>`).join('');if(state.transferProgram){const x=state.programs.find(p=>p.id===state.transferProgram);if(!x)$('#transferCard').insertAdjacentHTML('beforeend',`<option value="${escape(state.transferProgram)}">Tarjeta seleccionada · ${escape(state.transferProgram)}</option>`);$('#transferCard').value=state.transferProgram}document.querySelectorAll('[data-transfer-id]').forEach(el=>el.onclick=()=>{state.transferProgram=el.dataset.transferId;tab('transfer');$('#transferCard').value=state.transferProgram;$('#transferReview').classList.add('hidden')})}
async function load(){const d=await rpc('rewards_adminx_overview',{p_search:'',p_business_offset:0,p_program_offset:0});showStats(d.metrics);await Promise.all([loadBusiness(),loadPrograms()])}
async function loadBusiness(){const d=await rpc('rewards_adminx_overview',{p_search:state.businessSearch,p_business_offset:state.bo,p_program_offset:0});state.businesses=d.businesses||[];state.businessTotal=d.business_total;renderBusiness()}
async function loadPrograms(){const d=await rpc('rewards_adminx_overview',{p_search:state.programSearch,p_business_offset:0,p_program_offset:state.po});state.programs=d.programs||[];state.programTotal=d.program_total;renderPrograms()}
function openPlan(b){state.modalBusiness=b;$('#modalAccount').textContent=b.business_name+' · '+b.email;$('#modalPlan').value=b.manual_plan||b.rewards_plan;$('#modal').classList.remove('hidden')}
function closePlan(){$('#modal').classList.add('hidden');state.modalBusiness=null}
async function assignPlan(){const b=state.modalBusiness,plan=$('#modalPlan').value;if(!b)return;if(!confirm(`¿Asignar ${plans[plan]} a ${b.business_name}? ${plan==='trial'?'Se retirará el plan de cortesía.':'No se generará ningún cobro.'}`))return;const btn=$('#confirmPlan');btn.disabled=true;try{await rpc('rewards_adminx_assign_plan',{p_business_id:b.id,p_plan:plan});closePlan();notice('Plan actualizado para '+b.business_name+'.',true);await load()}catch(e){notice(e.message)}finally{btn.disabled=false}}
async function targetSearch(){const term=$('#targetSearch').value.trim();if(!term)throw new Error('Escribe el nombre o correo del negocio destino.');const d=await rpc('rewards_adminx_overview',{p_search:term,p_business_offset:0,p_program_offset:0});$('#targetBusiness').innerHTML='<option value="">Selecciona el negocio destino</option>'+(d.businesses||[]).map(b=>`<option value="${escape(b.id)}">${escape(b.business_name)} · ${escape(b.email)} · ${escape(plans[b.rewards_plan]||b.rewards_plan)}</option>`).join('');if(!(d.businesses||[]).length)notice('No hay negocios con esa búsqueda. Verifica que el cliente haya creado su cuenta.');else if(d.business_total>50)notice('Hay muchos resultados; precisa el correo para encontrar al cliente correcto.');$('#transferReview').classList.add('hidden')}
async function transferPreview(){const id=$('#transferCard').value,target=$('#targetBusiness').value;if(!id||!target)throw new Error('Selecciona tarjeta y cuenta destino.');const d=await rpc('rewards_adminx_transfer_preview',{p_program_id:id,p_target_business_id:target});const review=$('#transferReview');review.className='review'+(d.new_status!==d.old_status?' warn':'');review.innerHTML=`<h3>Revisa antes de confirmar</h3><p><strong>${escape(d.card)}</strong> → <strong>${escape(d.target_business)}</strong> (${escape(plans[d.target_plan]||d.target_plan)})</p><p>Se transfieren ${fmt(d.customers)} clientes, ${fmt(d.transactions)} movimientos, ${fmt(d.staff)} empleados y ${fmt(d.notifications)} registros de notificaciones.</p><p><strong>Estado: ${escape(d.old_status)} → ${escape(d.new_status)}</strong></p>${d.old_status!==d.new_status?'<p>El plan de destino no permite conservar esta tarjeta publicada. Se transferirá como borrador, conservando los registros.</p>':''}<button class="primary" id="confirmTransfer">Confirmar transferencia completa</button>`;$('#confirmTransfer').onclick=async()=>{if(!confirm('¿Confirmas transferir esta tarjeta y todos sus registros a otro negocio? Esta acción cambia su propietario.'))return;const btn=$('#confirmTransfer');btn.disabled=true;try{const result=await rpc('rewards_adminx_transfer',{p_program_id:id,p_target_business_id:target});review.classList.add('hidden');notice(`Tarjeta transferida. ${result.customers} clientes, ${result.transactions} movimientos. Estado: ${result.status}.`,true);await load()}catch(e){notice('No se transfirió la tarjeta: '+e.message);btn.disabled=false}}}
function debounce(fn){let timer;return ()=>{clearTimeout(timer);timer=setTimeout(()=>fn().catch(e=>notice(e.message)),320)}}
function bind(){document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>tab(el.dataset.tab));document.querySelectorAll('[data-goto]').forEach(el=>el.onclick=()=>tab(el.dataset.goto));$('#businessSearch').oninput=debounce(()=>{state.businessSearch=$('#businessSearch').value.trim();state.bo=0;return loadBusiness()});$('#programSearch').oninput=debounce(()=>{state.programSearch=$('#programSearch').value.trim();state.po=0;return loadPrograms()});$('#businessPrev').onclick=()=>{state.bo=Math.max(0,state.bo-50);loadBusiness().catch(e=>notice(e.message))};$('#businessNext').onclick=()=>{state.bo+=50;loadBusiness().catch(e=>notice(e.message))};$('#programPrev').onclick=()=>{state.po=Math.max(0,state.po-50);loadPrograms().catch(e=>notice(e.message))};$('#programNext').onclick=()=>{state.po+=50;loadPrograms().catch(e=>notice(e.message))};$('#cancelModal').onclick=$('#closeModal').onclick=closePlan;$('#modal').onclick=e=>{if(e.target===$('#modal'))closePlan()};$('#confirmPlan').onclick=assignPlan;$('#searchTarget').onclick=()=>targetSearch().catch(e=>notice(e.message));$('#previewTransfer').onclick=()=>transferPreview().catch(e=>notice(e.message));$('#transferCard').onchange=e=>{state.transferProgram=e.target.value;$('#transferReview').classList.add('hidden')};$('#targetBusiness').onchange=()=>$('#transferReview').classList.add('hidden');$('#logout').onclick=async()=>{await sb.auth.signOut();location.href='/app/login.html'}}
(async()=>{try{if(!sb)throw new Error('Supabase no está configurado.');const {data:{user},error}=await sb.auth.getUser();if(error||!user){location.href='/app/login.html?next=%2Fadminx%2F';return}const isAdmin=await rpc('rewards_adminx_is_admin',{});if(!isAdmin){$('#loading').classList.add('hidden');$('#denied').classList.remove('hidden');return}$('#adminEmail').textContent=user.email;bind();await load();$('#loading').classList.add('hidden');$('#app').classList.remove('hidden')}catch(e){$('#loading').textContent='No se pudo abrir Adminx: '+e.message+' · Verifica que ejecutaste 016J-adminx.sql.'}})();
})();
